- id: fuel-plugin-iommu-sh
  type: shell
  role: '*' 
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  priority : 50 
  parameters:
    cmd: bash enable_iommu.sh
    retries: 3
    interval: 20
    timeout: 600

- id: fuel-plugin-qlogic-sriov-compute-reboot 
  role: ['compute'] 
  type: reboot
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  priority : 100
  parameters:
    timeout: 600

- id: fuel-plugin-qlogic-sriov-compute-deployment-sh
  type: shell
  role: ['compute']
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  priority : 101
  parameters:
    cmd: bash deploy_compute.sh
    retries: 3
    interval: 20
    timeout: 300

- id: fuel-plugin-qlogic-sriov-controller-deployment-sh
  type: shell
  role: ['primary-controller', 'controller']
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  priority : 102
  parameters:
    cmd: bash deploy_controller.sh 
    retries: 3
    interval: 20
    timeout: 300
