attributes:

   nic_10G:
    value: false
    label: 'Enable SR-IOV for QLogic NX2 10G Ethernet'
    Description: 'Enable SRIOV Support for QLogic NX2 10GbE Single and Dual Port Adapter'
    weight: 10
    type: 'checkbox'
   
   num_10G_vfs:
    value: '16'
    label: 'Number of VFs'
    description: 'Number of Virtual Functions to create on the Qlogic 10G NIC for single port with Link UP'
    weight: 11 
    type: 'text'
    regex:
      source: "^(6[0-4]|[1-5][0-9]|[1-9])$"
      error: "Invalid Virtual NICs number. Please use a number in the range of 1-64."
    restrictions:
    - condition: "settings:fuel-plugin-qlogic-sriov.nic_10G.value == false or settings:common.libvirt_type.value != 'kvm' or not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
      message: "For QLogic SR-IOV Plugin support in Compute Node, SRIOV should be enable for 10G NIC / Hypervisor Type Should be KVM / Networking should be Neutron/VLAN segmentation type."
   
   nic_vlan_support:
     value: false
     label: 'Enable VLAN for SRIOV-VF (10G)'
     Description: 'This will Create SRIOV-NS with VLAN Support'
     weight: 13
     type: 'checkbox'

   nic_10G_vlan_min_range:
     value: '2100'
     label: 'vlan start'
     description : 'Supported VLAN MIN Range for 10G NIC'
     weight: 14
     type: 'text'
     regex:
        source: "^(409[0-4]|40[0-8][0-9]|[1-3][0-9][0-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9]|[2-9])$"
        error : "Invalid VLAN Number. Please use number between 2-4094"
     restrictions:
     - condition: "(settings:fuel-plugin-qlogic-sriov.nic_10G.value == false and settings:fuel-plugin-qlogic-sriov.nic_vlan_support.value == false) or settings:common.libvirt_type.value != 'kvm' or not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"   
       message: "For QLogic SR-IOV Plugin support in Compute Node, SRIOV should be enable for 10G NIC / Hypervisor Type Should be KVM / Networking should be Neutron/VLAN segmentation type."
     min: 2
     max: "settings:fuel-plugin-qlogic-sriov.nic_10G_vlan_max_range.vlaue - 1"

   nic_10G_vlan_max_range:
     value: '2300'
     label: 'vlan end'
     description : 'Supported VLAN MAX Range for 10G NIC'
     weight: 16
     type: 'text'
     regex:
        source: "^(409[0-4]|40[0-8][0-9]|[1-3][0-9][0-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9]|[2-9])$"
        error : "Invalid VLAN Number. Please use number between 2-4094"
     restrictions:
     - condition: "(settings:fuel-plugin-qlogic-sriov.nic_10G.value == false and settings:fuel-plugin-qlogic-sriov.nic_vlan_support.value == false) or (settings:fuel-plugin-qlogic-sriov.nic_10G_vlan_max_range.value == settings:fuel-plugin-qlogic-sriov.nic_10G_vlan_min_range.value) or settings:common.libvirt_type.value != 'kvm' or not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"   
       message: "For QLogic SR-IOV Plugin support in Compute Node, SRIOV should be enable for 10G NIC / Hypervisor Type Should be KVM / Networking should be Neutron/VLAN segmentation type and VLAN MAX should be greater than VLAN MIN"
   
   nic_fastlinq:
     value: false
     label: 'Enable SR-IOV for QLogic 25G/40G/100G Ethernet'
     Description: 'Enable SRIOV Support for QLogic 25G/40G/100G Single and Dual Port Adapter'
     weight: 17
     type: 'checkbox'
   
   num_fastlinq_vfs:
     value: '16'
     label: 'Number of VFs'
     description: 'Number of Virtual Functions to create on the Qlogic 25G/40G/100G NIC for single  port with Link UP'
     weight: 18 
     type: 'text'
     regex:
        source: "^(6[0-4]|[1-5][0-9]|[1-9])$"
        error: "Invalid Virtual NICs number. Please use a number in the range of 1-64."
     restrictions:
     - condition: "settings:fuel-plugin-qlogic-sriov.nic_fastlinq.value == false or settings:common.libvirt_type.value != 'kvm' or not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
       message: "For QLogic SR-IOV Plugin support in Compute Node, SRIOV should be enable for 25G NIC / Hypervisor Type Should be KVM / Networking should be Neutron/VLAN segmentation type."

   nic_fastlinq_vlan_support:
     value: false
     label: 'Enable VLAN for SRIOV-VF (25G/40G/100G)'
     Description: 'This will Create SRIOV-NS with VLAN Support'
     weight: 20
     type: 'checkbox'

   nic_fastlinq_vlan_min_range:
     value: '2100'
     label: 'vlan start'
     description : 'Supported VLAN MIN Range for 25G/40G/100G NIC'
     weight: 21
     type: 'text'
     regex:
        source: "^(409[0-4]|40[0-8][0-9]|[1-3][0-9][0-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9]|[2-9])$"
        error : "Invalid VLAN Number. Please use number between 2-4094"
     restrictions:
     - condition: "(settings:fuel-plugin-qlogic-sriov.nic_fastlinq.value == false and settings:fuel-plugin-qlogic-sriov.nic_fastlinq_vlan_support.value == false) or settings:common.libvirt_type.value != 'kvm' or not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
       message: "For QLogic SR-IOV Plugin support in Compute Node, SRIOV should be enable for 25G/40G/100G NIC / Hypervisor Type Should be KVM / Networking should be Neutron/VLAN segmentation type."
     min: 2
     max: "settings:fuel-plugin-qlogic-sriov.nic_fastlinq_vlan_max_range.vlaue - 1"

   nic_fastlinq_vlan_max_range:
     value: '2300'
     label: 'vlan end'
     description : 'Supported VLAN MAX Range for 25G/40G/100G NIC'
     weight: 22
     type: 'text'
     regex:
        source: "^(409[0-4]|40[0-8][0-9]|[1-3][0-9][0-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9]|[2-9])$"
        error : "Invalid VLAN Number. Please use number between 2-4094"
     restrictions:
     - condition: "(settings:fuel-plugin-qlogic-sriov.nic_fastlinq.value == false and settings:fuel-plugin-qlogic-sriov.nic_fastlinq_vlan_support.value == false) or (settings:fuel-plugin-qlogic-sriov.nic_fastlinq_vlan_max_range.value == settings:fuel-plugin-qlogic-sriov.nic_fastlinq_vlan_min_range.value) or settings:common.libvirt_type.value != 'kvm' or not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
       message: "For QLogic SR-IOV Plugin support in Compute Node, SRIOV should be enable for 25G/40G/100G NIC / Hypervisor Type Should be KVM / Networking should be Neutron/VLAN segmentation type and VLAN MAX should be greater than VLAN MIN"

