#!/bin/bash
FUEL_BOOTSTRAP_DIR="/var/www/nailgun/bootstraps/active_bootstrap/"
BACKUP_BOOTSTRAP_NUMBER_FILE="/tmp/bootstrap_backup"
BOOTSTRAP_CLI_YAML_FILE="/etc/fuel-bootstrap-cli/fuel_bootstrap_cli.yaml"
BACKUP_BOOTSTRAP_CLI_YAML_FILE="/etc/fuel-bootstrap-cli/fuel_bootstrap_cli.yaml.bkup"
FASTLINQ_REPO_DIR="/var/www/nailgun/fastlinq_repo/ubuntu"
FUEL_PLUGIN_DIR="/var/www/nailgun/plugins/fuel-plugin-qlogic-sriov*"
FUEL_MASTER_IP=`hostname`

active_bootstrap=`fuel-bootstrap list | grep active | cut -d "|" -f2`
if [ ! -z $active_bootstrap ]; then
	echo $active_bootstrap > $BACKUP_BOOTSTRAP_NUMBER_FILE
	echo "Backup Current Active Bootstrap Image"
fi

if [ -f $BOOTSTRAP_CLI_YAML_FILE ]; then
	cp $BOOTSTRAP_CLI_YAML_FILE $BACKUP_BOOTSTRAP_CLI_YAML_FILE
	echo "Backup Current Bootstrap cli yaml file"
fi

if [ ! -d $FASTLINQ_REPO_DIR ]; then
	mkdir -p $FASTLINQ_REPO_DIR
fi
	# installed dpkg-dev package, if it is not there
	yum -y install dpkg-dev

	# create repo meta-data
        cp -f $FUEL_PLUGIN_DIR/deployment_scripts/debpackage/fastlinq-dkms*.deb $FASTLINQ_REPO_DIR 
	pushd $FASTLINQ_REPO_DIR
	dpkg-scanpackages ./ /dev/null | gzip -9c > Packages.gz
        popd

	# Create Release file
	echo -e "Origin: user_custom\nLabel: custom\nSuite: user_custom\nCodename: \
        user_custom\nArchitectures: amd64\nComponents: main\nDescription: custom" \
        > $FASTLINQ_REPO_DIR/Release

if grep "fastlinq_repo" $BOOTSTRAP_CLI_YAML_FILE
then
	echo "fatlinq_repo already exist in Bootstrap cli yaml file"
else
	echo "Adding fastlinq_repor in Bootstrap cli yaml file"
	sed -i  '/skip_default_img_build:/i'"\    - name: fastlinq_repo"'\n'"\      priority: 1002"'\n'"\      section:"' ""'""'\n'"\      suite: ./"'\n'"\      type: deb"'\n'"\      uri: "'"http://'$FUEL_MASTER_IP':8080/fastlinq_repo/ubuntu/"'""'\n' $BOOTSTRAP_CLI_YAML_FILE
fi
	
fuel-bootstrap --verbose --debug build --package fastlinq-dkms --label fastlinq_bootstrap --extra-dir $FUEL_PLUGIN_DIR/startup_scripts/ --script $FUEL_PLUGIN_DIR/startup_scripts/startup.sh --activate 2>&1 | tee /tmp/fastlinq_bootstrap.log

dockerctl shell cobbler cobbler sync
